before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
bundler_args: --without development production --quiet
install: ./install-test-project.sh 
script: "bundle exec rspec spec"
rvm:
  - 2.2.1

# whitelist
branches:
  only:
    - master
    - 2-4-stable
