class Spree::IdealCountryUtil
  def self.format_locale(locale)
    case locale
      when "ar"
        return "ar_AR"
      when "cs"
        return "cs_CZ"
      when "dk"
        return "dk_DK"
      when "de"
        return "de_DE"
      when "es"
        return "es_ES"
      when "fi"
        return "fi_FI"
      when "fr"
        return "fr_FR"
      when "hu"
        return "hu_HU"
      when "it"
        return "it_IT"
      when "ja"
        return "ja_JP"
      when "ko"
        return "ko_KR"
      when "nl"
        return "nl_NL"
      when "no"
        return "no_NO"
      when "pl"
        return "pl_PL"
      when "pt"
        return "pt_PT"
      when "ru"
        return "ru_RU"
      when "se"
        return "se_SE"
      when "sk"
        return "sk_SK"
      when "tr"
        return "tr_TR"
      when "zh"
        return "zh_CN"
      else
        return "en_US"
    end
  end
end